[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[font]
size = 8

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Italic"

[font.normal]
family = "MonoLisa"
style = "Light"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(steam:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

#[schemes.dracula.bright]
#black = "0x4d4d4d"
#blue = "0xcaa9fa"
#cyan = "0x9aedfe"
#green = "0x5af78e"
#magenta = "0xff92d0"
#red = "0xff6e67"
#white = "0xe6e6e6"
#yellow = "0xf4f99d"
#
#[schemes.dracula.cursor]
#cursor = "CellForeground"
#text = "CellBackground"
#
#[schemes.dracula.dim]
#black = "0x14151b"
#blue = "0x4d5b86"
#cyan = "0x59dffc"
#green = "0x1ef956"
#magenta = "0xff46b0"
#red = "0xff2222"
#white = "0xe6e6d1"
#yellow = "0xebf85b"
#
#[schemes.dracula.line_indicator]
#background = "None"
#foreground = "None"
#
#[schemes.dracula.normal]
#black = "0x000000"
#blue = "0xbd93f9"
#cyan = "0x8be9fd"
#green = "0x50fa7b"
#magenta = "0xff79c6"
#red = "0xff5555"
#white = "0xbfbfbf"
#yellow = "0xf1fa8c"
#
#[schemes.dracula.primary]
#background = "0x282a36"
#foreground = "0xf8f8f2"
#
#[schemes.dracula.search.bar]
#background = "0x282a36"
#foreground = "0xf8f8f2"
#
#[schemes.dracula.search.focused_match]
#background = "0xffb86c"
#foreground = "0x44475a"
#
#[schemes.dracula.search.matches]
#background = "0x50fa7b"
#foreground = "0x44475a"
#
#[schemes.dracula.selection]
#background = "0x44475a"
#text = "CellForeground"
#
#[schemes.dracula.vi_mode_cursor]
#cursor = "CellForeground"
#text = "CellBackground"
#
#[schemes.gruvbox.bright]
#black = "#928374"
#blue = "#83a598"
#cyan = "#8ec07c"
#green = "#b8bb26"
#magenta = "#d3869b"
#red = "#fb4934"
#white = "#ebdbb2"
#yellow = "#fabd2f"
#
#[schemes.gruvbox.normal]
#black = "#282828"
#blue = "#458588"
#cyan = "#689d6a"
#green = "#98971a"
#magenta = "#b16286"
#red = "#cc241d"
#white = "#a89984"
#yellow = "#d79921"
#
#[schemes.gruvbox.primary]
#background = "#1d2021"
#foreground = "#ebdbb2"
#
#[schemes.gruvbox_hard_dark.bright]
#black = "0x928374"
#blue = "0x83a598"
#cyan = "0x8ec07c"
#green = "0xb8bb26"
#magenta = "0xd3869b"
#red = "0xfb4934"
#white = "0xebdbb2"
#yellow = "0xfabd2f"
#
#[schemes.gruvbox_hard_dark.normal]
#black = "0x282828"
#blue = "0x458588"
#cyan = "0x689d6a"
#green = "0x98971a"
#magenta = "0xb16286"
#red = "0xcc241d"
#white = "0xa89984"
#yellow = "0xd79921"
#
#[schemes.gruvbox_hard_dark.primary]
#background = "0x1d2021"
#foreground = "0xebdbb2"
#
#[schemes.gruvbox_light.bright]
#black = "0x928374"
#blue = "0x076678"
#cyan = "0x427b58"
#green = "0x79740e"
#magenta = "0x8f3f71"
#red = "0x9d0006"
#white = "0x3c3836"
#yellow = "0xb57614"
#
#[schemes.gruvbox_light.normal]
#black = "0xfbf1c7"
#blue = "0x458588"
#cyan = "0x689d6a"
#green = "0x98971a"
#magenta = "0xb16286"
#red = "0xcc241d"
#white = "0x7c6f64"
#yellow = "0xd79921"
#
#[schemes.gruvbox_light.primary]
#background = "0xfbf1c7"
#foreground = "0x3c3836"

[window.padding]
x = 5
y = 0
