#format = "$directory$character$git_branch$git_status"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break$character"""
right_format = """
$rust\
$c\
$nodejs\
$golang\
$docker_context\
"""
add_newline = false

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_blue"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[hostname]
ssh_only = false
format = '[@](fg:color_aqua)[$hostname](fg:color_yellow)[:](fg:color_red)'
disabled = false

[username]
show_always = true
style_user = "fg:color_purple"
style_root = "fg:color_red"
format = '[$user]($style)'

[directory]
style = "fg:color_aqua"
format = "[ $path/ ]($style)"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"

#[directory.substitutions]
#"Documents" = "󰈙"
#"Downloads" = ""
#"Music" = "󰝚"
#"Pictures" = ""
#"code" = "󰲋"

[git_branch]
#symbol = ""
style = "fg:color_blue"
format = '[|](fg:color_red)[[ $symbol$branch ](fg:color_blue)]($style)'

[git_status]
style = "fg:color_aqua"
format = '[[($all_status$ahead_behind)](fg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "fg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_aqua)]($style)'

[c]
symbol = " "
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[rust]
symbol = ""
style = "fg:color_red"
format = '[[ $symbol( $version) ](fg:color_red)]($style)'

[golang]
symbol = ""
style = "fg:color_green"
format = '[[ $symbol( $version) ](fg:color_green)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
