[env]
TERM = "alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.primary]
#background = "#1d2021"
background = "#1c1c1c"
foreground = "#ebdbb2"

[font]
size = 8

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "ExtraLight Italic"

[font.normal]
family = "MonoLisa"
style = "ExtraLight"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(steam:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window.padding]
x = 0
y = 0
