# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#export ZSH_THEME="gentoo"
export ZSH_THEME="pygmalion"
#export ZSH_THEME='lukerandall'
#export ZSH_THEME='simple'
#export ZSH_THEME=""

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"
#INTERACTIVE_COMMENTS="true"
setopt interactivecomments
# Comment this out to disable weekly auto-update checks
#DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
export DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
#
zstyle :omz:plugins:ssh-agent lifetime 48h
zstyle :omz:plugins:ssh-agent agent-forwarding on

plugins=(pip python systemadmin ssh-agent)

# Customize to your needs...
# .zshrc
#
autoload -Uz compinit
compinit

#if command -v tmux >/dev/null 2>&1; then
tm() {
    [[ -z "$1" ]] && { echo "usage: tm <session>" >&2; return 1; }
    tmux has -t $1 && tmux attach -t $1 || tmux new -s $1
}

function __tmux-sessions() {
    local expl
    local -a sessions
    sessions=( ${${(f)"$(command tmux list-sessions)"}/:[ $'\t']##/:} )
    _describe -t sessions 'sessions' sessions "$@"
}
#fi

compdef __tmux-sessions tm

export EDITOR="nvim"
export GIT_EDITOR="nvim"

setopt histignorespace

test -d $HOME/.local/bin && export PATH="$HOME/.local/bin:$PATH"
test -d $HOME/.cargo && {
    export PATH="$HOME/.cargo/bin:$PATH"
    alias ca='cargo'

    plugins=($plugins rust)
}

# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
test -d $HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && {
    plugins=($plugins zsh-autosuggestions)
}


test -d /usr/local/go/bin && {
    export GOPATH=$HOME/.go
    export GOBIN=$GOPATH/bin
    export PATH="$GOBIN:/usr/local/go/bin:$PATH"

    plugins=($plugins golang)
}

[[ $commands[git] ]] && plugins=($plugins git)
[[ $commands[docker] ]] && plugins=($plugins docker)
[[ $commands[docker-compose] ]] && plugins=($plugins docker-compose)
[[ $commands[rsync] ]] && plugins=($plugins rsync)
[[ $commands[gpg-agent] ]] && plugins=($plugins gpg-agent)
[[ $commands[rg] ]] && plugins=($plugins ripgrep)
[[ $commands[plz] ]] && plugins=($plugins please)
[[ $commands[kubectl] ]] && plugins=($plugins kubectl)

test -f $HOME/.zshrc.platform  && source $HOME/.zshrc.platform
test -f $HOME/.zshrc.local && source $HOME/.zshrc.local

source $ZSH/oh-my-zsh.sh

[[ $commands[eza] ]] && {
    alias ls='eza --sort=type'                                                         # ls
    alias l='eza -lbG --git --sort=type'                                               # list, size, type, git
    alias ll='eza -lbF --git --sort=type'                                              # long list
    alias llm='eza -lbF --git --sort=modified'                                         # long list, modified date sort
    alias la='eza -lbhHigUmuSa --time-style=long-iso --git --color-scale --sort=type'  # all list
    alias lx='eza -lbhHigUmuSa@ --time-style=long-iso --git --color-scale --sort=type' # all + extended list

    # speciality views
    alias lS='eza -1 --sort=type'                                                      # one column, just names
    alias lt='eza --tree --level=2 --sort=type'                                        # tree
}

[[ $commands[bat] ]] && {
    alias cat='bat'

    function batdiff() {
        git rev-parse --git-dir > /dev/null 2>&1 && git diff --name-only --diff-filter=d | xargs bat --diff
    }
}

[[ $commands[zoxide] ]] && {
    eval "$(zoxide init zsh)"
}

export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"

test -f $HOME/.zshrc.post.local && source $HOME/.zshrc.post.local
